Feature/refactor blogApplication
satomi212/blog-application pull request #3
Opened 2022-03-13 15:13 UTC by satomi212

ブランチ名をアプリ自体に命名し、コミットをファイルごとに分けてみました。
お手隙で確認お願いします！

2022-03-14 04:46 UTC, KatsuyaTanaka95 requested changes

2022-03-14 04:46 UTC, KatsuyaTanaka95 commented on src/public/user/completeSignup.php
> +session_start();
こちらsessionを使う直前で書きましょう！！！
離れたとこに書いてあると、「これどこのために使っているんだろう？？？」的な感じになってしまうので。。。。。。
使う直前で書くことで、
- レビュアーがレビューしやすい
- 他の人がコードを読みやすい
- 自分自身も見返した時にコードが読みやすい
というメリットがありますよ〜〜〜〜😁

2022-03-14 04:46 UTC, KatsuyaTanaka95 commented on src/public/user/completeSignup.php
>  }
スニペットのような感じでバリデーションを書きましょう！！！✌
スニペットの書き方だと、エラーだとわかったらそのタイミングでページ遷移して余計な処理を実行しないようになっています！！！！
このような書き方を「ガード節」と言います！！！
なるべく「ガード節」になるようにコードを書くときに意識してみてください！！！😁

2022-03-14 04:46 UTC, KatsuyaTanaka95 commented on src/public/user/completeSignin.php
> +
こちらのバリデーションも修正しましょう！

2022-03-14 23:30 UTC, aoi0038 commented
Slackで
「プッシュ時にif文の中括弧が勝手に追加されてしまいます。」
とおっしゃっていましたが、どのファイルの何行目のことでしょうか？？🤔

2022-03-15 12:00 UTC, aoi0038 commented
ディレクトリ構造の修正してみましょうか😊

2022-03-15 13:47 UTC, merged